version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/   # This is the web server's root directory (adjust if necessary)
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
